image: rust:1.40

.rust_cache: &rust_cache
  cache:
    paths:
      - .cargo/
      - target/

stages:
    - test
    - rustfmt
    - clippy
    - deploy

test:
  <<: *rust_cache
  script:
    - cargo check --verbose --all
    - cargo test --verbose --all
rustfmt:
  <<: *rust_cache
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
clippy:
  <<: *rust_cache
  script:
    - rustup component add clippy
    - cargo clippy --all

pages:
  image: rust:1.40
  stage: deploy
  only:
    - master
  script:
    - cargo doc --document-private-items
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
    - cp misc/index.html public
  artifacts:
    paths:
    - public
