image: rust:1.64

.rust_cache: &rust_cache
  cache:
    paths:
      - .cargo/
      - target/

stages:
    - test
    - rustfmt
    - deploy

test:
  <<: *rust_cache
  script:
    - apt update
    - apt install -y libsdl2-dev libsdl2-gfx-dev libsdl2-mixer-dev cmake
    - cargo check --verbose --all
    - cargo test --verbose --all

rustfmt:
 <<: *rust_cache
 script:
   - rustup component add rustfmt
   - cargo fmt --all -- --check

#clippy:
#  <<: *rust_cache
#  script:
#    - rustup component add clippy
#    - cargo clippy --all

pages:
  image: rust:1.58
  stage: deploy
  only:
    - main
  script:
    - apt update
    - apt install -y libsdl2-dev libsdl2-gfx-dev cmake
    - cargo doc --document-private-items --no-deps --workspace
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
    - cp misc/index.html public
  artifacts:
    paths:
      - public
