[package]
name = "gameplay"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "../build.rs"

[features]
null_check = []

[dependencies]
sound-traits.workspace = true
sound-sdl2.workspace = true
wad.workspace = true
glam.workspace = true
log.workspace = true
